server:
  port: 8000

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        # Not needed since we excluded the dependency
        enabled: false
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: http://localhost:8080/
          predicates:
            - Path=/attempts/**,/challenges/**,/users/**
        - id: gamification
          uri: http://localhost:8081/
          predicates:
            - Path=/leaderboards
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace