server:
  port: 8000

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: multiplication
          uri: http://localhost:8080/
          predicates:
            - Path=/attempts/**,/challenges/**,/users/**
        - id: gamification
          uri: http://localhost:8081/
          predicates:
            - Path=/leaderboards
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace